# Generated by Django 4.2.5 on 2023-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='daxil edilecek ad')),
                ('surname', models.CharField(max_length=255, verbose_name='daxil edilecek ad')),
                ('age', models.CharField(max_length=255, verbose_name='daxil edilecek yas')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'daxil edilecek ad',
                'verbose_name_plural': 'daxil edilecek adlar',
                'ordering': ('add_date',),
            },
        ),
    ]
